{{- if .Values.alternateReportStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.alternateReportStorage.volumeName }}
  namespace: trivy-system
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.alternateReportStorage.storageClassName }}
  storageClassName: {{ .Values.alternateReportStorage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.alternateReportStorage.storage }}
{{- end }}