{{- if and (eq .Values.serviceMonitor.enabled true) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "trivy-operator.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default (include "trivy-operator.namespace" . ) }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml .Values.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "trivy-operator.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels }}
      {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
    - {{ include "trivy-operator.namespace" . }}
  {{- end }}
  selector:
    matchLabels: {{- include "trivy-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - honorLabels: {{ .Values.serviceMonitor.honorLabels }}
    port: metrics
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    scheme: http
    {{- if .Values.serviceMonitor.endpointAdditionalProperties }}
    {{- with .Values.serviceMonitor.endpointAdditionalProperties }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}
