{{- if .Values.operator.builtInTrivyServer}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy
    app.kubernetes.io/instance: trivy
    app.kubernetes.io/version: "0.34.4"

data:
  TRIVY_LISTEN: "0.0.0.0:4954"
  TRIVY_CACHE_DIR: "/home/scanner/.cache/trivy"
  TRIVY_DEBUG: "false"
  TRIVY_SKIP_UPDATE: "false"
  TRIVY_DB_REPOSITORY: "ghcr.io/aquasecurity/trivy-db"

---
apiVersion: v1
kind: Secret
metadata:
  name: trivy
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy
    helm.sh/chart: trivy-0.4.17
    app.kubernetes.io/instance: trivy
    app.kubernetes.io/version: "0.34.0"
type: Opaque
data:
  GITHUB_TOKEN: ""
  TRIVY_TOKEN: ""
  TRIVY_USERNAME: ""
  TRIVY_PASSWORD: ""

---
apiVersion: v1
kind: Service
metadata:
  name: trivy
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy
    app.kubernetes.io/instance: trivy
    app.kubernetes.io/version: "0.34.0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trivy
    app.kubernetes.io/instance: trivy
  ports:
    - name: trivy-http
      protocol: TCP
      port: 4954
      targetPort: 4954
  sessionAffinity: ClientIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trivy
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy
    helm.sh/chart: trivy-0.4.17
    app.kubernetes.io/instance: trivy
    app.kubernetes.io/version: "0.34.0"
spec:
  podManagementPolicy: "Parallel"
  serviceName: trivy
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy
      app.kubernetes.io/instance: trivy
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: 
  template:
    metadata:
      annotations:
        checksum/config: 7fcc66ace3f98462349856795765021e7bf7a0106f28439a9f6dc74257404370
      labels:
        app.kubernetes.io/name: trivy
        app.kubernetes.io/instance: trivy
    spec:
      serviceAccountName: trivy-operator
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: main
          image: docker.io/aquasec/trivy:0.34.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          args:
            - server
          envFrom:
            - configMapRef:
                name: trivy
            - secretRef:
                name: trivy
          ports:
            - name: trivy-http
              containerPort: 4954
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: trivy-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: trivy-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp-data
              readOnly: false
            - mountPath: /home/scanner/.cache
              name: data
              readOnly: false
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: tmp-data
          emptyDir: {}
{{- end}}