---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      k8s:
        patterns:
          - "*k8s*"
      testcontainers:
        patterns:
          - github.com/testcontainers/*
      common:
        patterns:
          - "*"
      golang:
        patterns:
          - go*
      aqua:
        patterns:
          - "*aquasecurity*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
