# .github/release.yml

changelog:
  categories:
    - title: ✨ Notable Changes ✨
      labels:
        - feature
    - title: 🐛 Notable Fixes 🐛
      labels:
        - bug
    - title: 🔧 Docs && Updateds 📝	
      labels:
        - documentation
        - misc
    - title: 👒 Dependencies 👒
      labels:
        - deps
      