linters:
  enable:
    - errorlint
    - gocritic
    - gosec
    - misspell
linters-settings:
  gocritic:
    enabled-checks:
      - importShadow
  misspell:
    locale: US
    ignore-words:
      - "importas" # linter name
run:
  timeout: 5m
