run:
  timeout: 5m
linters:
  enable:
    - errorlint
    - govet
    - gosec
    - gocritic
  disable:
    - gosimple
    - ineffassign
    - staticcheck
linters-settings:
  gocritic:
    enabled-checks:
      - importShadow
