linters:
  disable:
    - structcheck # FIXME: Currently doesn't work on Go 1.18: https://github.com/golangci/golangci-lint/issues/2649
  enable:
    - errorlint
    - gocritic
    - gosec
    # - unparam FIXME: Currently doesn't work on Go 1.18: https://github.com/golangci/golangci-lint/issues/2649
linters-settings:
  gocritic:
    enabled-checks:
      - importShadow
run:
  timeout: 5m
