version: 2

project_name: trivy_operator
release:
  draft: false
  prerelease: auto
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: trivy-operator
    main: ./cmd/trivy-operator/main.go
    binary: trivy-operator
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - ppc64le
    goarm:
      - "7"
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ end }}
    builds:
      - trivy-operator
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .FullCommit }}"
changelog:
  filters:
    exclude:
      - '^test'
      - '^release'
  sort: asc
  use: github
  groups:
    - title: ✨ Notable Changes ✨
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 🐛 Notable Fixes 🐛
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 👮 Security updates👮
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 📝 Documentation 📝
      regexp: ^.*?docs(\([[:word:]]+\))??!?:.+$
      order: 250
    - title: 🔧 Miscellaneous 🔧
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 👷 Other work 👷
      order: 9999
dockers:
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-amd64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-amd64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile
    goarch: amd64
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/amd64"
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-ubi8-amd64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-amd64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-amd64"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile.ubi8
    goarch: amd64
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/amd64"
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-arm64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-arm64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-arm64"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile
    goarch: arm64
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/arm64"
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-ubi8-arm64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-arm64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-arm64"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile.ubi8
    goarch: arm64
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/arm64"
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-s390x"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-s390x"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-s390x"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile
    goarch: s390x
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/s390x"
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-ppc64le"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ppc64le"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ppc64le"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile
    goarch: ppc64le
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/ppc64le"
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-ubi8-s390x"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-s390x"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-s390x"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile.ubi8
    goarch: s390x
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/s390x"
  - image_templates:
      - "docker.io/aquasec/trivy-operator:{{ .Version }}-ubi8-ppc64le"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-ppc64le"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-ppc64le"
    use: buildx
    goos: linux
    dockerfile: build/trivy-operator/Dockerfile.ubi8
    goarch: ppc64le
    ids:
      - trivy-operator
    build_flag_templates:
      - "--label=org.opencontainers.image.title=trivy-operator"
      - "--label=org.opencontainers.image.description=Keeps trivy-operator resources updated"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/trivy-operator"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.documentation=https://aquasecurity.github.io/trivy-operator/v{{ .Version }}/"
      - "--platform=linux/ppc64le"
docker_manifests:
  - name_template: "aquasec/trivy-operator:{{ .Version }}"
    image_templates:
      - "aquasec/trivy-operator:{{ .Version }}-amd64"
      - "aquasec/trivy-operator:{{ .Version }}-arm64"
      - "aquasec/trivy-operator:{{ .Version }}-s390x"
      - "aquasec/trivy-operator:{{ .Version }}-ppc64le"
  - name_template: "aquasec/trivy-operator:{{ .Version }}-ubi8"
    image_templates:
      - "aquasec/trivy-operator:{{ .Version }}-ubi8-amd64"
      - "aquasec/trivy-operator:{{ .Version }}-ubi8-arm64"
      - "aquasec/trivy-operator:{{ .Version }}-ubi8-s390x"
      - "aquasec/trivy-operator:{{ .Version }}-ubi8-ppc64le"
  - name_template: "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}"
    image_templates:
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-amd64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-arm64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-s390x"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ppc64le"
  - name_template: "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8"
    image_templates:
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-amd64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-arm64"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-s390x"
      - "public.ecr.aws/aquasecurity/trivy-operator:{{ .Version }}-ubi8-ppc64le"
#  - name_template: "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}"
#    image_templates:
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-amd64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-arm64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-s390x"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ppc64le"
#  - name_template: "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8"
#    image_templates:
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-amd64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-arm64"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-s390x"
#      - "ghcr.io/aquasecurity/trivy-operator:{{ .Version }}-ubi8-ppc64le"

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: all
    output: true

docker_signs:
  - cmd: cosign
    args:
      - "sign"
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "${artifact}"
    artifacts: all
    output: true
