apiVersion: v1
kind: Pod
metadata:
  name: scan-vulnerabilityreport-test
  namespace: trivy-system
spec:
  containers:
  - args:
    - -c
    - trivy image nginx:1.20.0 --cache-dir /tmp/trivy/.cache --format json --image-config-scanners
      secret --scanners vuln,secret --skip-db-update --slow --list-all-pkgs --config
      /etc/trivy/trivy.yaml --output /tmp/scan/result_test-containers.json 2>/tmp/scan/result_test-containers.json.log
      && bzip2 -c /tmp/scan/result_test-containers.json | base64
    command:
    - /bin/sh
    env:
    - name: TRIVY_SEVERITY
      valueFrom:
        configMapKeyRef:
          key: trivy.severity
          name: trivy-operator-trivy-config
          optional: true
    - name: TRIVY_IGNORE_UNFIXED
      valueFrom:
        configMapKeyRef:
          key: trivy.ignoreUnfixed
          name: trivy-operator-trivy-config
          optional: true
    - name: TRIVY_OFFLINE_SCAN
      valueFrom:
        configMapKeyRef:
          key: trivy.offlineScan
          name: trivy-operator-trivy-config
          optional: true
    - name: TRIVY_JAVA_DB_REPOSITORY
      valueFrom:
        configMapKeyRef:
          key: trivy.javaDbRepository
          name: trivy-operator-trivy-config
          optional: true
    - name: TRIVY_TIMEOUT
      valueFrom:
        configMapKeyRef:
          key: trivy.timeout
          name: trivy-operator-trivy-config
          optional: true
    - name: TRIVY_SKIP_FILES
      valueFrom:
        configMapKeyRef:
          key: trivy.skipFiles
          name: trivy-operator-trivy-config
          optional: true
    - name: TRIVY_SKIP_DIRS
      valueFrom:
        configMapKeyRef:
          key: trivy.skipDirs
          name: trivy-operator-trivy-config
          optional: true
    - name: HTTP_PROXY
      valueFrom:
        configMapKeyRef:
          key: trivy.httpProxy
          name: trivy-operator-trivy-config
          optional: true
    - name: HTTPS_PROXY
      valueFrom:
        configMapKeyRef:
          key: trivy.httpsProxy
          name: trivy-operator-trivy-config
          optional: true
    - name: NO_PROXY
      valueFrom:
        configMapKeyRef:
          key: trivy.noProxy
          name: trivy-operator-trivy-config
          optional: true
    image: mirror.gcr.io/aquasec/trivy:0.64.1
    imagePullPolicy: IfNotPresent
    name: test-containers
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /tmp/scan
      name: scanresult
    - mountPath: /etc/trivy/trivy.yaml
      name: configfile
      subPath: trivy.yaml
    - mountPath: /tmp/trivy-vex
      name: vex-data-volume
      readOnly: true
  dnsPolicy: ClusterFirst
  initContainers:
  - args:
    - --cache-dir
    - /tmp/trivy/.cache
    - image
    - --download-db-only
    - --db-repository
    - mirror.gcr.io/aquasec/trivy-db
    - --config
    - /etc/trivy/trivy.yaml
    command:
    - trivy
    env:
    - name: HTTP_PROXY
      valueFrom:
        configMapKeyRef:
          key: trivy.httpProxy
          name: trivy-operator-trivy-config
          optional: true
    - name: HTTPS_PROXY
      valueFrom:
        configMapKeyRef:
          key: trivy.httpsProxy
          name: trivy-operator-trivy-config
          optional: true
    - name: NO_PROXY
      valueFrom:
        configMapKeyRef:
          key: trivy.noProxy
          name: trivy-operator-trivy-config
          optional: true
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: trivy.githubToken
          name: trivy-operator-trivy-config
          optional: true
    image: mirror.gcr.io/aquasec/trivy:0.64.1
    imagePullPolicy: IfNotPresent
    name: aa5efc9a-bf2d-4acb-9239-0b34e0688362
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /tmp/trivy-vex
      name: vex-data-volume
      readOnly: true
    - mountPath: /etc/trivy/trivy.yaml
      name: configfile
      subPath: trivy.yaml
  volumes:
  - emptyDir: {}
    name: tmp
  - emptyDir: {}
    name: scanresult
  - configMap:
      defaultMode: 420
      items:
      - key: trivy.configFile
        path: trivy.yaml
      name: trivy-operator-trivy-config
    name: configfile
  - configMap:
      defaultMode: 420
      name: trivy-vex-files
    name: vex-data-volume
status:
  