targetNamespaces: "trivy-system"

image:
  registry: docker.io
  repository: aquasecurity/trivy-operator
  tag: dev
  pullPolicy: Never

trivy:
  configFile:
    vulnerability:
      vex:
        - /tmp/trivy-vex/flink.openvex.json

trivyOperator:
  scanJobCustomVolumes:
    - name: vex-data-volume
      configMap:
        name: trivy-vex-files

  scanJobCustomVolumesMount:
    - name: vex-data-volume
      mountPath: /tmp/trivy-vex
      readOnly: true
    - name: configfile
      mountPath: /etc/trivy/trivy.yaml
      subPath: trivy.yaml

