//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	types "github.com/aquasecurity/trivy-db/pkg/types"
	shared "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/shared"
	v1beta1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterVulnerabilityReport)(nil), (*v1beta1.ClusterVulnerabilityReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterVulnerabilityReport_To_v1beta1_ClusterVulnerabilityReport(a.(*ClusterVulnerabilityReport), b.(*v1beta1.ClusterVulnerabilityReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterVulnerabilityReport)(nil), (*ClusterVulnerabilityReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterVulnerabilityReport_To_v1alpha1_ClusterVulnerabilityReport(a.(*v1beta1.ClusterVulnerabilityReport), b.(*ClusterVulnerabilityReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterVulnerabilityReportList)(nil), (*v1beta1.ClusterVulnerabilityReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterVulnerabilityReportList_To_v1beta1_ClusterVulnerabilityReportList(a.(*ClusterVulnerabilityReportList), b.(*v1beta1.ClusterVulnerabilityReportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterVulnerabilityReportList)(nil), (*ClusterVulnerabilityReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterVulnerabilityReportList_To_v1alpha1_ClusterVulnerabilityReportList(a.(*v1beta1.ClusterVulnerabilityReportList), b.(*ClusterVulnerabilityReportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Vulnerability)(nil), (*v1beta1.Vulnerability)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Vulnerability_To_v1beta1_Vulnerability(a.(*Vulnerability), b.(*v1beta1.Vulnerability), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Vulnerability)(nil), (*Vulnerability)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Vulnerability_To_v1alpha1_Vulnerability(a.(*v1beta1.Vulnerability), b.(*Vulnerability), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VulnerabilityReport)(nil), (*v1beta1.VulnerabilityReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VulnerabilityReport_To_v1beta1_VulnerabilityReport(a.(*VulnerabilityReport), b.(*v1beta1.VulnerabilityReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VulnerabilityReport)(nil), (*VulnerabilityReport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VulnerabilityReport_To_v1alpha1_VulnerabilityReport(a.(*v1beta1.VulnerabilityReport), b.(*VulnerabilityReport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VulnerabilityReportData)(nil), (*v1beta1.VulnerabilityReportData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VulnerabilityReportData_To_v1beta1_VulnerabilityReportData(a.(*VulnerabilityReportData), b.(*v1beta1.VulnerabilityReportData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VulnerabilityReportData)(nil), (*VulnerabilityReportData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VulnerabilityReportData_To_v1alpha1_VulnerabilityReportData(a.(*v1beta1.VulnerabilityReportData), b.(*VulnerabilityReportData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VulnerabilityReportList)(nil), (*v1beta1.VulnerabilityReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VulnerabilityReportList_To_v1beta1_VulnerabilityReportList(a.(*VulnerabilityReportList), b.(*v1beta1.VulnerabilityReportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VulnerabilityReportList)(nil), (*VulnerabilityReportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VulnerabilityReportList_To_v1alpha1_VulnerabilityReportList(a.(*v1beta1.VulnerabilityReportList), b.(*VulnerabilityReportList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClusterVulnerabilityReport_To_v1beta1_ClusterVulnerabilityReport(in *ClusterVulnerabilityReport, out *v1beta1.ClusterVulnerabilityReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VulnerabilityReportData_To_v1beta1_VulnerabilityReportData(&in.Report, &out.Report, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterVulnerabilityReport_To_v1beta1_ClusterVulnerabilityReport is an autogenerated conversion function.
func Convert_v1alpha1_ClusterVulnerabilityReport_To_v1beta1_ClusterVulnerabilityReport(in *ClusterVulnerabilityReport, out *v1beta1.ClusterVulnerabilityReport, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterVulnerabilityReport_To_v1beta1_ClusterVulnerabilityReport(in, out, s)
}

func autoConvert_v1beta1_ClusterVulnerabilityReport_To_v1alpha1_ClusterVulnerabilityReport(in *v1beta1.ClusterVulnerabilityReport, out *ClusterVulnerabilityReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_VulnerabilityReportData_To_v1alpha1_VulnerabilityReportData(&in.Report, &out.Report, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_ClusterVulnerabilityReport_To_v1alpha1_ClusterVulnerabilityReport is an autogenerated conversion function.
func Convert_v1beta1_ClusterVulnerabilityReport_To_v1alpha1_ClusterVulnerabilityReport(in *v1beta1.ClusterVulnerabilityReport, out *ClusterVulnerabilityReport, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterVulnerabilityReport_To_v1alpha1_ClusterVulnerabilityReport(in, out, s)
}

func autoConvert_v1alpha1_ClusterVulnerabilityReportList_To_v1beta1_ClusterVulnerabilityReportList(in *ClusterVulnerabilityReportList, out *v1beta1.ClusterVulnerabilityReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.ClusterVulnerabilityReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterVulnerabilityReportList_To_v1beta1_ClusterVulnerabilityReportList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterVulnerabilityReportList_To_v1beta1_ClusterVulnerabilityReportList(in *ClusterVulnerabilityReportList, out *v1beta1.ClusterVulnerabilityReportList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterVulnerabilityReportList_To_v1beta1_ClusterVulnerabilityReportList(in, out, s)
}

func autoConvert_v1beta1_ClusterVulnerabilityReportList_To_v1alpha1_ClusterVulnerabilityReportList(in *v1beta1.ClusterVulnerabilityReportList, out *ClusterVulnerabilityReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterVulnerabilityReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ClusterVulnerabilityReportList_To_v1alpha1_ClusterVulnerabilityReportList is an autogenerated conversion function.
func Convert_v1beta1_ClusterVulnerabilityReportList_To_v1alpha1_ClusterVulnerabilityReportList(in *v1beta1.ClusterVulnerabilityReportList, out *ClusterVulnerabilityReportList, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterVulnerabilityReportList_To_v1alpha1_ClusterVulnerabilityReportList(in, out, s)
}

func autoConvert_v1alpha1_Vulnerability_To_v1beta1_Vulnerability(in *Vulnerability, out *v1beta1.Vulnerability, s conversion.Scope) error {
	out.VulnerabilityID = in.VulnerabilityID
	out.Resource = in.Resource
	out.InstalledVersion = in.InstalledVersion
	out.FixedVersion = in.FixedVersion
	out.PublishedDate = in.PublishedDate
	out.LastModifiedDate = in.LastModifiedDate
	out.Severity = shared.Severity(in.Severity)
	out.Title = in.Title
	out.Description = in.Description
	out.CVSSSource = in.CVSSSource
	out.PrimaryLink = in.PrimaryLink
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	out.Score = (*float64)(unsafe.Pointer(in.Score))
	out.Target = in.Target
	out.CVSS = *(*types.VendorCVSS)(unsafe.Pointer(&in.CVSS))
	out.Class = in.Class
	out.PackageType = in.PackageType
	out.PkgPath = in.PkgPath
	out.PkgPURL = in.PkgPURL
	return nil
}

// Convert_v1alpha1_Vulnerability_To_v1beta1_Vulnerability is an autogenerated conversion function.
func Convert_v1alpha1_Vulnerability_To_v1beta1_Vulnerability(in *Vulnerability, out *v1beta1.Vulnerability, s conversion.Scope) error {
	return autoConvert_v1alpha1_Vulnerability_To_v1beta1_Vulnerability(in, out, s)
}

func autoConvert_v1beta1_Vulnerability_To_v1alpha1_Vulnerability(in *v1beta1.Vulnerability, out *Vulnerability, s conversion.Scope) error {
	out.VulnerabilityID = in.VulnerabilityID
	out.Resource = in.Resource
	out.InstalledVersion = in.InstalledVersion
	out.FixedVersion = in.FixedVersion
	out.PublishedDate = in.PublishedDate
	out.LastModifiedDate = in.LastModifiedDate
	out.Severity = shared.Severity(in.Severity)
	out.Title = in.Title
	out.Description = in.Description
	out.CVSSSource = in.CVSSSource
	out.PrimaryLink = in.PrimaryLink
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	out.Score = (*float64)(unsafe.Pointer(in.Score))
	out.Target = in.Target
	out.CVSS = *(*types.VendorCVSS)(unsafe.Pointer(&in.CVSS))
	out.Class = in.Class
	out.PackageType = in.PackageType
	out.PkgPath = in.PkgPath
	out.PkgPURL = in.PkgPURL
	return nil
}

// Convert_v1beta1_Vulnerability_To_v1alpha1_Vulnerability is an autogenerated conversion function.
func Convert_v1beta1_Vulnerability_To_v1alpha1_Vulnerability(in *v1beta1.Vulnerability, out *Vulnerability, s conversion.Scope) error {
	return autoConvert_v1beta1_Vulnerability_To_v1alpha1_Vulnerability(in, out, s)
}

func autoConvert_v1alpha1_VulnerabilityReport_To_v1beta1_VulnerabilityReport(in *VulnerabilityReport, out *v1beta1.VulnerabilityReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_VulnerabilityReportData_To_v1beta1_VulnerabilityReportData(&in.Report, &out.Report, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_VulnerabilityReport_To_v1beta1_VulnerabilityReport is an autogenerated conversion function.
func Convert_v1alpha1_VulnerabilityReport_To_v1beta1_VulnerabilityReport(in *VulnerabilityReport, out *v1beta1.VulnerabilityReport, s conversion.Scope) error {
	return autoConvert_v1alpha1_VulnerabilityReport_To_v1beta1_VulnerabilityReport(in, out, s)
}

func autoConvert_v1beta1_VulnerabilityReport_To_v1alpha1_VulnerabilityReport(in *v1beta1.VulnerabilityReport, out *VulnerabilityReport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_VulnerabilityReportData_To_v1alpha1_VulnerabilityReportData(&in.Report, &out.Report, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_VulnerabilityReport_To_v1alpha1_VulnerabilityReport is an autogenerated conversion function.
func Convert_v1beta1_VulnerabilityReport_To_v1alpha1_VulnerabilityReport(in *v1beta1.VulnerabilityReport, out *VulnerabilityReport, s conversion.Scope) error {
	return autoConvert_v1beta1_VulnerabilityReport_To_v1alpha1_VulnerabilityReport(in, out, s)
}

func autoConvert_v1alpha1_VulnerabilityReportData_To_v1beta1_VulnerabilityReportData(in *VulnerabilityReportData, out *v1beta1.VulnerabilityReportData, s conversion.Scope) error {
	out.UpdateTimestamp = in.UpdateTimestamp
	out.Scanner = in.Scanner
	out.Registry = in.Registry
	out.Artifact = in.Artifact
	out.OS = in.OS
	out.Summary = in.Summary
	out.Vulnerabilities = *(*[]v1beta1.Vulnerability)(unsafe.Pointer(&in.Vulnerabilities))
	return nil
}

// Convert_v1alpha1_VulnerabilityReportData_To_v1beta1_VulnerabilityReportData is an autogenerated conversion function.
func Convert_v1alpha1_VulnerabilityReportData_To_v1beta1_VulnerabilityReportData(in *VulnerabilityReportData, out *v1beta1.VulnerabilityReportData, s conversion.Scope) error {
	return autoConvert_v1alpha1_VulnerabilityReportData_To_v1beta1_VulnerabilityReportData(in, out, s)
}

func autoConvert_v1beta1_VulnerabilityReportData_To_v1alpha1_VulnerabilityReportData(in *v1beta1.VulnerabilityReportData, out *VulnerabilityReportData, s conversion.Scope) error {
	out.UpdateTimestamp = in.UpdateTimestamp
	out.Scanner = in.Scanner
	out.Registry = in.Registry
	out.Artifact = in.Artifact
	out.OS = in.OS
	out.Summary = in.Summary
	out.Vulnerabilities = *(*[]Vulnerability)(unsafe.Pointer(&in.Vulnerabilities))
	return nil
}

// Convert_v1beta1_VulnerabilityReportData_To_v1alpha1_VulnerabilityReportData is an autogenerated conversion function.
func Convert_v1beta1_VulnerabilityReportData_To_v1alpha1_VulnerabilityReportData(in *v1beta1.VulnerabilityReportData, out *VulnerabilityReportData, s conversion.Scope) error {
	return autoConvert_v1beta1_VulnerabilityReportData_To_v1alpha1_VulnerabilityReportData(in, out, s)
}

func autoConvert_v1alpha1_VulnerabilityReportList_To_v1beta1_VulnerabilityReportList(in *VulnerabilityReportList, out *v1beta1.VulnerabilityReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.VulnerabilityReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_VulnerabilityReportList_To_v1beta1_VulnerabilityReportList is an autogenerated conversion function.
func Convert_v1alpha1_VulnerabilityReportList_To_v1beta1_VulnerabilityReportList(in *VulnerabilityReportList, out *v1beta1.VulnerabilityReportList, s conversion.Scope) error {
	return autoConvert_v1alpha1_VulnerabilityReportList_To_v1beta1_VulnerabilityReportList(in, out, s)
}

func autoConvert_v1beta1_VulnerabilityReportList_To_v1alpha1_VulnerabilityReportList(in *v1beta1.VulnerabilityReportList, out *VulnerabilityReportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VulnerabilityReport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_VulnerabilityReportList_To_v1alpha1_VulnerabilityReportList is an autogenerated conversion function.
func Convert_v1beta1_VulnerabilityReportList_To_v1alpha1_VulnerabilityReportList(in *v1beta1.VulnerabilityReportList, out *VulnerabilityReportList, s conversion.Scope) error {
	return autoConvert_v1beta1_VulnerabilityReportList_To_v1alpha1_VulnerabilityReportList(in, out, s)
}
