apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trivy-operator.yaml
images:
  - name: docker.io/aquasec/trivy-operator
    newName: docker.io/aquasec/trivy-operator
    newTag: dev
