apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trivy-operator.yaml

# Remove the trivy-operator deployment to avoid conflicts with the test suite.
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: trivy-operator
        namespace: trivy-system
      $patch: delete
