// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterSbomReportsGetter has a method to return a ClusterSbomReportInterface.
// A group's client should implement this interface.
type ClusterSbomReportsGetter interface {
	ClusterSbomReports(namespace string) ClusterSbomReportInterface
}

// ClusterSbomReportInterface has methods to work with ClusterSbomReport resources.
type ClusterSbomReportInterface interface {
	Create(ctx context.Context, clusterSbomReport *aquasecurityv1alpha1.ClusterSbomReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.ClusterSbomReport, error)
	Update(ctx context.Context, clusterSbomReport *aquasecurityv1alpha1.ClusterSbomReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ClusterSbomReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.ClusterSbomReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.ClusterSbomReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.ClusterSbomReport, err error)
	ClusterSbomReportExpansion
}

// clusterSbomReports implements ClusterSbomReportInterface
type clusterSbomReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.ClusterSbomReport, *aquasecurityv1alpha1.ClusterSbomReportList]
}

// newClusterSbomReports returns a ClusterSbomReports
func newClusterSbomReports(c *AquasecurityV1alpha1Client, namespace string) *clusterSbomReports {
	return &clusterSbomReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.ClusterSbomReport, *aquasecurityv1alpha1.ClusterSbomReportList](
			"clustersbomreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.ClusterSbomReport { return &aquasecurityv1alpha1.ClusterSbomReport{} },
			func() *aquasecurityv1alpha1.ClusterSbomReportList {
				return &aquasecurityv1alpha1.ClusterSbomReportList{}
			},
		),
	}
}
