// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterConfigAuditReportsGetter has a method to return a ClusterConfigAuditReportInterface.
// A group's client should implement this interface.
type ClusterConfigAuditReportsGetter interface {
	ClusterConfigAuditReports(namespace string) ClusterConfigAuditReportInterface
}

// ClusterConfigAuditReportInterface has methods to work with ClusterConfigAuditReport resources.
type ClusterConfigAuditReportInterface interface {
	Create(ctx context.Context, clusterConfigAuditReport *aquasecurityv1alpha1.ClusterConfigAuditReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.ClusterConfigAuditReport, error)
	Update(ctx context.Context, clusterConfigAuditReport *aquasecurityv1alpha1.ClusterConfigAuditReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ClusterConfigAuditReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.ClusterConfigAuditReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.ClusterConfigAuditReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.ClusterConfigAuditReport, err error)
	ClusterConfigAuditReportExpansion
}

// clusterConfigAuditReports implements ClusterConfigAuditReportInterface
type clusterConfigAuditReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.ClusterConfigAuditReport, *aquasecurityv1alpha1.ClusterConfigAuditReportList]
}

// newClusterConfigAuditReports returns a ClusterConfigAuditReports
func newClusterConfigAuditReports(c *AquasecurityV1alpha1Client, namespace string) *clusterConfigAuditReports {
	return &clusterConfigAuditReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.ClusterConfigAuditReport, *aquasecurityv1alpha1.ClusterConfigAuditReportList](
			"clusterconfigauditreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.ClusterConfigAuditReport {
				return &aquasecurityv1alpha1.ClusterConfigAuditReport{}
			},
			func() *aquasecurityv1alpha1.ClusterConfigAuditReportList {
				return &aquasecurityv1alpha1.ClusterConfigAuditReportList{}
			},
		),
	}
}
