// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterComplianceReportsGetter has a method to return a ClusterComplianceReportInterface.
// A group's client should implement this interface.
type ClusterComplianceReportsGetter interface {
	ClusterComplianceReports(namespace string) ClusterComplianceReportInterface
}

// ClusterComplianceReportInterface has methods to work with ClusterComplianceReport resources.
type ClusterComplianceReportInterface interface {
	Create(ctx context.Context, clusterComplianceReport *aquasecurityv1alpha1.ClusterComplianceReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.ClusterComplianceReport, error)
	Update(ctx context.Context, clusterComplianceReport *aquasecurityv1alpha1.ClusterComplianceReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ClusterComplianceReport, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterComplianceReport *aquasecurityv1alpha1.ClusterComplianceReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ClusterComplianceReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.ClusterComplianceReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.ClusterComplianceReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.ClusterComplianceReport, err error)
	ClusterComplianceReportExpansion
}

// clusterComplianceReports implements ClusterComplianceReportInterface
type clusterComplianceReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.ClusterComplianceReport, *aquasecurityv1alpha1.ClusterComplianceReportList]
}

// newClusterComplianceReports returns a ClusterComplianceReports
func newClusterComplianceReports(c *AquasecurityV1alpha1Client, namespace string) *clusterComplianceReports {
	return &clusterComplianceReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.ClusterComplianceReport, *aquasecurityv1alpha1.ClusterComplianceReportList](
			"clustercompliancereports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.ClusterComplianceReport {
				return &aquasecurityv1alpha1.ClusterComplianceReport{}
			},
			func() *aquasecurityv1alpha1.ClusterComplianceReportList {
				return &aquasecurityv1alpha1.ClusterComplianceReportList{}
			},
		),
	}
}
