// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterRbacAssessmentReportsGetter has a method to return a ClusterRbacAssessmentReportInterface.
// A group's client should implement this interface.
type ClusterRbacAssessmentReportsGetter interface {
	ClusterRbacAssessmentReports(namespace string) ClusterRbacAssessmentReportInterface
}

// ClusterRbacAssessmentReportInterface has methods to work with ClusterRbacAssessmentReport resources.
type ClusterRbacAssessmentReportInterface interface {
	Create(ctx context.Context, clusterRbacAssessmentReport *aquasecurityv1alpha1.ClusterRbacAssessmentReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.ClusterRbacAssessmentReport, error)
	Update(ctx context.Context, clusterRbacAssessmentReport *aquasecurityv1alpha1.ClusterRbacAssessmentReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ClusterRbacAssessmentReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.ClusterRbacAssessmentReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.ClusterRbacAssessmentReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.ClusterRbacAssessmentReport, err error)
	ClusterRbacAssessmentReportExpansion
}

// clusterRbacAssessmentReports implements ClusterRbacAssessmentReportInterface
type clusterRbacAssessmentReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.ClusterRbacAssessmentReport, *aquasecurityv1alpha1.ClusterRbacAssessmentReportList]
}

// newClusterRbacAssessmentReports returns a ClusterRbacAssessmentReports
func newClusterRbacAssessmentReports(c *AquasecurityV1alpha1Client, namespace string) *clusterRbacAssessmentReports {
	return &clusterRbacAssessmentReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.ClusterRbacAssessmentReport, *aquasecurityv1alpha1.ClusterRbacAssessmentReportList](
			"clusterrbacassessmentreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.ClusterRbacAssessmentReport {
				return &aquasecurityv1alpha1.ClusterRbacAssessmentReport{}
			},
			func() *aquasecurityv1alpha1.ClusterRbacAssessmentReportList {
				return &aquasecurityv1alpha1.ClusterRbacAssessmentReportList{}
			},
		),
	}
}
