// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterInfraAssessmentReportsGetter has a method to return a ClusterInfraAssessmentReportInterface.
// A group's client should implement this interface.
type ClusterInfraAssessmentReportsGetter interface {
	ClusterInfraAssessmentReports(namespace string) ClusterInfraAssessmentReportInterface
}

// ClusterInfraAssessmentReportInterface has methods to work with ClusterInfraAssessmentReport resources.
type ClusterInfraAssessmentReportInterface interface {
	Create(ctx context.Context, clusterInfraAssessmentReport *aquasecurityv1alpha1.ClusterInfraAssessmentReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.ClusterInfraAssessmentReport, error)
	Update(ctx context.Context, clusterInfraAssessmentReport *aquasecurityv1alpha1.ClusterInfraAssessmentReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ClusterInfraAssessmentReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.ClusterInfraAssessmentReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.ClusterInfraAssessmentReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.ClusterInfraAssessmentReport, err error)
	ClusterInfraAssessmentReportExpansion
}

// clusterInfraAssessmentReports implements ClusterInfraAssessmentReportInterface
type clusterInfraAssessmentReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.ClusterInfraAssessmentReport, *aquasecurityv1alpha1.ClusterInfraAssessmentReportList]
}

// newClusterInfraAssessmentReports returns a ClusterInfraAssessmentReports
func newClusterInfraAssessmentReports(c *AquasecurityV1alpha1Client, namespace string) *clusterInfraAssessmentReports {
	return &clusterInfraAssessmentReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.ClusterInfraAssessmentReport, *aquasecurityv1alpha1.ClusterInfraAssessmentReportList](
			"clusterinfraassessmentreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.ClusterInfraAssessmentReport {
				return &aquasecurityv1alpha1.ClusterInfraAssessmentReport{}
			},
			func() *aquasecurityv1alpha1.ClusterInfraAssessmentReportList {
				return &aquasecurityv1alpha1.ClusterInfraAssessmentReportList{}
			},
		),
	}
}
