// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ConfigAuditReportsGetter has a method to return a ConfigAuditReportInterface.
// A group's client should implement this interface.
type ConfigAuditReportsGetter interface {
	ConfigAuditReports(namespace string) ConfigAuditReportInterface
}

// ConfigAuditReportInterface has methods to work with ConfigAuditReport resources.
type ConfigAuditReportInterface interface {
	Create(ctx context.Context, configAuditReport *aquasecurityv1alpha1.ConfigAuditReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.ConfigAuditReport, error)
	Update(ctx context.Context, configAuditReport *aquasecurityv1alpha1.ConfigAuditReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ConfigAuditReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.ConfigAuditReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.ConfigAuditReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.ConfigAuditReport, err error)
	ConfigAuditReportExpansion
}

// configAuditReports implements ConfigAuditReportInterface
type configAuditReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.ConfigAuditReport, *aquasecurityv1alpha1.ConfigAuditReportList]
}

// newConfigAuditReports returns a ConfigAuditReports
func newConfigAuditReports(c *AquasecurityV1alpha1Client, namespace string) *configAuditReports {
	return &configAuditReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.ConfigAuditReport, *aquasecurityv1alpha1.ConfigAuditReportList](
			"configauditreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.ConfigAuditReport { return &aquasecurityv1alpha1.ConfigAuditReport{} },
			func() *aquasecurityv1alpha1.ConfigAuditReportList {
				return &aquasecurityv1alpha1.ConfigAuditReportList{}
			},
		),
	}
}
