// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ExposedSecretReportsGetter has a method to return a ExposedSecretReportInterface.
// A group's client should implement this interface.
type ExposedSecretReportsGetter interface {
	ExposedSecretReports(namespace string) ExposedSecretReportInterface
}

// ExposedSecretReportInterface has methods to work with ExposedSecretReport resources.
type ExposedSecretReportInterface interface {
	Create(ctx context.Context, exposedSecretReport *aquasecurityv1alpha1.ExposedSecretReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.ExposedSecretReport, error)
	Update(ctx context.Context, exposedSecretReport *aquasecurityv1alpha1.ExposedSecretReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.ExposedSecretReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.ExposedSecretReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.ExposedSecretReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.ExposedSecretReport, err error)
	ExposedSecretReportExpansion
}

// exposedSecretReports implements ExposedSecretReportInterface
type exposedSecretReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.ExposedSecretReport, *aquasecurityv1alpha1.ExposedSecretReportList]
}

// newExposedSecretReports returns a ExposedSecretReports
func newExposedSecretReports(c *AquasecurityV1alpha1Client, namespace string) *exposedSecretReports {
	return &exposedSecretReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.ExposedSecretReport, *aquasecurityv1alpha1.ExposedSecretReportList](
			"exposedsecretreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.ExposedSecretReport { return &aquasecurityv1alpha1.ExposedSecretReport{} },
			func() *aquasecurityv1alpha1.ExposedSecretReportList {
				return &aquasecurityv1alpha1.ExposedSecretReportList{}
			},
		),
	}
}
