// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterComplianceReportExpansion interface{}

type ClusterConfigAuditReportExpansion interface{}

type ClusterInfraAssessmentReportExpansion interface{}

type ClusterRbacAssessmentReportExpansion interface{}

type ClusterSbomReportExpansion interface{}

type ClusterVulnerabilityReportExpansion interface{}

type ConfigAuditReportExpansion interface{}

type ExposedSecretReportExpansion interface{}

type InfraAssessmentReportExpansion interface{}

type RbacAssessmentReportExpansion interface{}

type SbomReportExpansion interface{}

type VulnerabilityReportExpansion interface{}
