// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InfraAssessmentReportsGetter has a method to return a InfraAssessmentReportInterface.
// A group's client should implement this interface.
type InfraAssessmentReportsGetter interface {
	InfraAssessmentReports(namespace string) InfraAssessmentReportInterface
}

// InfraAssessmentReportInterface has methods to work with InfraAssessmentReport resources.
type InfraAssessmentReportInterface interface {
	Create(ctx context.Context, infraAssessmentReport *aquasecurityv1alpha1.InfraAssessmentReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.InfraAssessmentReport, error)
	Update(ctx context.Context, infraAssessmentReport *aquasecurityv1alpha1.InfraAssessmentReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.InfraAssessmentReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.InfraAssessmentReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.InfraAssessmentReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.InfraAssessmentReport, err error)
	InfraAssessmentReportExpansion
}

// infraAssessmentReports implements InfraAssessmentReportInterface
type infraAssessmentReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.InfraAssessmentReport, *aquasecurityv1alpha1.InfraAssessmentReportList]
}

// newInfraAssessmentReports returns a InfraAssessmentReports
func newInfraAssessmentReports(c *AquasecurityV1alpha1Client, namespace string) *infraAssessmentReports {
	return &infraAssessmentReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.InfraAssessmentReport, *aquasecurityv1alpha1.InfraAssessmentReportList](
			"infraassessmentreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.InfraAssessmentReport {
				return &aquasecurityv1alpha1.InfraAssessmentReport{}
			},
			func() *aquasecurityv1alpha1.InfraAssessmentReportList {
				return &aquasecurityv1alpha1.InfraAssessmentReportList{}
			},
		),
	}
}
