// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RbacAssessmentReportsGetter has a method to return a RbacAssessmentReportInterface.
// A group's client should implement this interface.
type RbacAssessmentReportsGetter interface {
	RbacAssessmentReports(namespace string) RbacAssessmentReportInterface
}

// RbacAssessmentReportInterface has methods to work with RbacAssessmentReport resources.
type RbacAssessmentReportInterface interface {
	Create(ctx context.Context, rbacAssessmentReport *aquasecurityv1alpha1.RbacAssessmentReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.RbacAssessmentReport, error)
	Update(ctx context.Context, rbacAssessmentReport *aquasecurityv1alpha1.RbacAssessmentReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.RbacAssessmentReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.RbacAssessmentReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.RbacAssessmentReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.RbacAssessmentReport, err error)
	RbacAssessmentReportExpansion
}

// rbacAssessmentReports implements RbacAssessmentReportInterface
type rbacAssessmentReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.RbacAssessmentReport, *aquasecurityv1alpha1.RbacAssessmentReportList]
}

// newRbacAssessmentReports returns a RbacAssessmentReports
func newRbacAssessmentReports(c *AquasecurityV1alpha1Client, namespace string) *rbacAssessmentReports {
	return &rbacAssessmentReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.RbacAssessmentReport, *aquasecurityv1alpha1.RbacAssessmentReportList](
			"rbacassessmentreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.RbacAssessmentReport { return &aquasecurityv1alpha1.RbacAssessmentReport{} },
			func() *aquasecurityv1alpha1.RbacAssessmentReportList {
				return &aquasecurityv1alpha1.RbacAssessmentReportList{}
			},
		),
	}
}
