// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	scheme "github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SbomReportsGetter has a method to return a SbomReportInterface.
// A group's client should implement this interface.
type SbomReportsGetter interface {
	SbomReports(namespace string) SbomReportInterface
}

// SbomReportInterface has methods to work with SbomReport resources.
type SbomReportInterface interface {
	Create(ctx context.Context, sbomReport *aquasecurityv1alpha1.SbomReport, opts v1.CreateOptions) (*aquasecurityv1alpha1.SbomReport, error)
	Update(ctx context.Context, sbomReport *aquasecurityv1alpha1.SbomReport, opts v1.UpdateOptions) (*aquasecurityv1alpha1.SbomReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*aquasecurityv1alpha1.SbomReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*aquasecurityv1alpha1.SbomReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *aquasecurityv1alpha1.SbomReport, err error)
	SbomReportExpansion
}

// sbomReports implements SbomReportInterface
type sbomReports struct {
	*gentype.ClientWithList[*aquasecurityv1alpha1.SbomReport, *aquasecurityv1alpha1.SbomReportList]
}

// newSbomReports returns a SbomReports
func newSbomReports(c *AquasecurityV1alpha1Client, namespace string) *sbomReports {
	return &sbomReports{
		gentype.NewClientWithList[*aquasecurityv1alpha1.SbomReport, *aquasecurityv1alpha1.SbomReportList](
			"sbomreports",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *aquasecurityv1alpha1.SbomReport { return &aquasecurityv1alpha1.SbomReport{} },
			func() *aquasecurityv1alpha1.SbomReportList { return &aquasecurityv1alpha1.SbomReportList{} },
		),
	}
}
