// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeExposedSecretReports implements ExposedSecretReportInterface
type fakeExposedSecretReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ExposedSecretReport, *v1alpha1.ExposedSecretReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeExposedSecretReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.ExposedSecretReportInterface {
	return &fakeExposedSecretReports{
		gentype.NewFakeClientWithList[*v1alpha1.ExposedSecretReport, *v1alpha1.ExposedSecretReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("exposedsecretreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ExposedSecretReport"),
			func() *v1alpha1.ExposedSecretReport { return &v1alpha1.ExposedSecretReport{} },
			func() *v1alpha1.ExposedSecretReportList { return &v1alpha1.ExposedSecretReportList{} },
			func(dst, src *v1alpha1.ExposedSecretReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ExposedSecretReportList) []*v1alpha1.ExposedSecretReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ExposedSecretReportList, items []*v1alpha1.ExposedSecretReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
