// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterComplianceReports implements ClusterComplianceReportInterface
type fakeClusterComplianceReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ClusterComplianceReport, *v1alpha1.ClusterComplianceReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeClusterComplianceReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.ClusterComplianceReportInterface {
	return &fakeClusterComplianceReports{
		gentype.NewFakeClientWithList[*v1alpha1.ClusterComplianceReport, *v1alpha1.ClusterComplianceReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clustercompliancereports"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterComplianceReport"),
			func() *v1alpha1.ClusterComplianceReport { return &v1alpha1.ClusterComplianceReport{} },
			func() *v1alpha1.ClusterComplianceReportList { return &v1alpha1.ClusterComplianceReportList{} },
			func(dst, src *v1alpha1.ClusterComplianceReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterComplianceReportList) []*v1alpha1.ClusterComplianceReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterComplianceReportList, items []*v1alpha1.ClusterComplianceReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
