// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeConfigAuditReports implements ConfigAuditReportInterface
type fakeConfigAuditReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ConfigAuditReport, *v1alpha1.ConfigAuditReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeConfigAuditReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.ConfigAuditReportInterface {
	return &fakeConfigAuditReports{
		gentype.NewFakeClientWithList[*v1alpha1.ConfigAuditReport, *v1alpha1.ConfigAuditReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("configauditreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ConfigAuditReport"),
			func() *v1alpha1.ConfigAuditReport { return &v1alpha1.ConfigAuditReport{} },
			func() *v1alpha1.ConfigAuditReportList { return &v1alpha1.ConfigAuditReportList{} },
			func(dst, src *v1alpha1.ConfigAuditReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ConfigAuditReportList) []*v1alpha1.ConfigAuditReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ConfigAuditReportList, items []*v1alpha1.ConfigAuditReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
