// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSbomReports implements SbomReportInterface
type fakeSbomReports struct {
	*gentype.FakeClientWithList[*v1alpha1.SbomReport, *v1alpha1.SbomReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeSbomReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.SbomReportInterface {
	return &fakeSbomReports{
		gentype.NewFakeClientWithList[*v1alpha1.SbomReport, *v1alpha1.SbomReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("sbomreports"),
			v1alpha1.SchemeGroupVersion.WithKind("SbomReport"),
			func() *v1alpha1.SbomReport { return &v1alpha1.SbomReport{} },
			func() *v1alpha1.SbomReportList { return &v1alpha1.SbomReportList{} },
			func(dst, src *v1alpha1.SbomReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SbomReportList) []*v1alpha1.SbomReport { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.SbomReportList, items []*v1alpha1.SbomReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
