// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterConfigAuditReports implements ClusterConfigAuditReportInterface
type fakeClusterConfigAuditReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ClusterConfigAuditReport, *v1alpha1.ClusterConfigAuditReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeClusterConfigAuditReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.ClusterConfigAuditReportInterface {
	return &fakeClusterConfigAuditReports{
		gentype.NewFakeClientWithList[*v1alpha1.ClusterConfigAuditReport, *v1alpha1.ClusterConfigAuditReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clusterconfigauditreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterConfigAuditReport"),
			func() *v1alpha1.ClusterConfigAuditReport { return &v1alpha1.ClusterConfigAuditReport{} },
			func() *v1alpha1.ClusterConfigAuditReportList { return &v1alpha1.ClusterConfigAuditReportList{} },
			func(dst, src *v1alpha1.ClusterConfigAuditReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterConfigAuditReportList) []*v1alpha1.ClusterConfigAuditReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterConfigAuditReportList, items []*v1alpha1.ClusterConfigAuditReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
