// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterRbacAssessmentReports implements ClusterRbacAssessmentReportInterface
type fakeClusterRbacAssessmentReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ClusterRbacAssessmentReport, *v1alpha1.ClusterRbacAssessmentReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeClusterRbacAssessmentReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.ClusterRbacAssessmentReportInterface {
	return &fakeClusterRbacAssessmentReports{
		gentype.NewFakeClientWithList[*v1alpha1.ClusterRbacAssessmentReport, *v1alpha1.ClusterRbacAssessmentReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clusterrbacassessmentreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterRbacAssessmentReport"),
			func() *v1alpha1.ClusterRbacAssessmentReport { return &v1alpha1.ClusterRbacAssessmentReport{} },
			func() *v1alpha1.ClusterRbacAssessmentReportList { return &v1alpha1.ClusterRbacAssessmentReportList{} },
			func(dst, src *v1alpha1.ClusterRbacAssessmentReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterRbacAssessmentReportList) []*v1alpha1.ClusterRbacAssessmentReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterRbacAssessmentReportList, items []*v1alpha1.ClusterRbacAssessmentReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
