// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterSbomReports implements ClusterSbomReportInterface
type fakeClusterSbomReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ClusterSbomReport, *v1alpha1.ClusterSbomReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeClusterSbomReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.ClusterSbomReportInterface {
	return &fakeClusterSbomReports{
		gentype.NewFakeClientWithList[*v1alpha1.ClusterSbomReport, *v1alpha1.ClusterSbomReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clustersbomreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterSbomReport"),
			func() *v1alpha1.ClusterSbomReport { return &v1alpha1.ClusterSbomReport{} },
			func() *v1alpha1.ClusterSbomReportList { return &v1alpha1.ClusterSbomReportList{} },
			func(dst, src *v1alpha1.ClusterSbomReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterSbomReportList) []*v1alpha1.ClusterSbomReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterSbomReportList, items []*v1alpha1.ClusterSbomReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
