// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeInfraAssessmentReports implements InfraAssessmentReportInterface
type fakeInfraAssessmentReports struct {
	*gentype.FakeClientWithList[*v1alpha1.InfraAssessmentReport, *v1alpha1.InfraAssessmentReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeInfraAssessmentReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.InfraAssessmentReportInterface {
	return &fakeInfraAssessmentReports{
		gentype.NewFakeClientWithList[*v1alpha1.InfraAssessmentReport, *v1alpha1.InfraAssessmentReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("infraassessmentreports"),
			v1alpha1.SchemeGroupVersion.WithKind("InfraAssessmentReport"),
			func() *v1alpha1.InfraAssessmentReport { return &v1alpha1.InfraAssessmentReport{} },
			func() *v1alpha1.InfraAssessmentReportList { return &v1alpha1.InfraAssessmentReportList{} },
			func(dst, src *v1alpha1.InfraAssessmentReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.InfraAssessmentReportList) []*v1alpha1.InfraAssessmentReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.InfraAssessmentReportList, items []*v1alpha1.InfraAssessmentReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
