// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterInfraAssessmentReports implements ClusterInfraAssessmentReportInterface
type fakeClusterInfraAssessmentReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ClusterInfraAssessmentReport, *v1alpha1.ClusterInfraAssessmentReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeClusterInfraAssessmentReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.ClusterInfraAssessmentReportInterface {
	return &fakeClusterInfraAssessmentReports{
		gentype.NewFakeClientWithList[*v1alpha1.ClusterInfraAssessmentReport, *v1alpha1.ClusterInfraAssessmentReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clusterinfraassessmentreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterInfraAssessmentReport"),
			func() *v1alpha1.ClusterInfraAssessmentReport { return &v1alpha1.ClusterInfraAssessmentReport{} },
			func() *v1alpha1.ClusterInfraAssessmentReportList { return &v1alpha1.ClusterInfraAssessmentReportList{} },
			func(dst, src *v1alpha1.ClusterInfraAssessmentReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterInfraAssessmentReportList) []*v1alpha1.ClusterInfraAssessmentReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterInfraAssessmentReportList, items []*v1alpha1.ClusterInfraAssessmentReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
