// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAquasecurityV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAquasecurityV1alpha1) ClusterComplianceReports(namespace string) v1alpha1.ClusterComplianceReportInterface {
	return newFakeClusterComplianceReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) ClusterConfigAuditReports(namespace string) v1alpha1.ClusterConfigAuditReportInterface {
	return newFakeClusterConfigAuditReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) ClusterInfraAssessmentReports(namespace string) v1alpha1.ClusterInfraAssessmentReportInterface {
	return newFakeClusterInfraAssessmentReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) ClusterRbacAssessmentReports(namespace string) v1alpha1.ClusterRbacAssessmentReportInterface {
	return newFakeClusterRbacAssessmentReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) ClusterSbomReports(namespace string) v1alpha1.ClusterSbomReportInterface {
	return newFakeClusterSbomReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) ClusterVulnerabilityReports(namespace string) v1alpha1.ClusterVulnerabilityReportInterface {
	return newFakeClusterVulnerabilityReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) ConfigAuditReports(namespace string) v1alpha1.ConfigAuditReportInterface {
	return newFakeConfigAuditReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) ExposedSecretReports(namespace string) v1alpha1.ExposedSecretReportInterface {
	return newFakeExposedSecretReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) InfraAssessmentReports(namespace string) v1alpha1.InfraAssessmentReportInterface {
	return newFakeInfraAssessmentReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) RbacAssessmentReports(namespace string) v1alpha1.RbacAssessmentReportInterface {
	return newFakeRbacAssessmentReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) SbomReports(namespace string) v1alpha1.SbomReportInterface {
	return newFakeSbomReports(c, namespace)
}

func (c *FakeAquasecurityV1alpha1) VulnerabilityReports(namespace string) v1alpha1.VulnerabilityReportInterface {
	return newFakeVulnerabilityReports(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAquasecurityV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
