// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/aquasecurity/trivy-operator/pkg/apis/aquasecurity/v1alpha1"
	aquasecurityv1alpha1 "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/aquasecurity/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRbacAssessmentReports implements RbacAssessmentReportInterface
type fakeRbacAssessmentReports struct {
	*gentype.FakeClientWithList[*v1alpha1.RbacAssessmentReport, *v1alpha1.RbacAssessmentReportList]
	Fake *FakeAquasecurityV1alpha1
}

func newFakeRbacAssessmentReports(fake *FakeAquasecurityV1alpha1, namespace string) aquasecurityv1alpha1.RbacAssessmentReportInterface {
	return &fakeRbacAssessmentReports{
		gentype.NewFakeClientWithList[*v1alpha1.RbacAssessmentReport, *v1alpha1.RbacAssessmentReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("rbacassessmentreports"),
			v1alpha1.SchemeGroupVersion.WithKind("RbacAssessmentReport"),
			func() *v1alpha1.RbacAssessmentReport { return &v1alpha1.RbacAssessmentReport{} },
			func() *v1alpha1.RbacAssessmentReportList { return &v1alpha1.RbacAssessmentReportList{} },
			func(dst, src *v1alpha1.RbacAssessmentReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.RbacAssessmentReportList) []*v1alpha1.RbacAssessmentReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.RbacAssessmentReportList, items []*v1alpha1.RbacAssessmentReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
