---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/managed-by: trivy-operator
    app.kubernetes.io/version: 0.1.0
  name: clustercompliancedetailreports.aquasecurity.github.io
spec:
  group: aquasecurity.github.io
  names:
    kind: ClusterComplianceDetailReport
    listKind: ClusterComplianceDetailReportList
    plural: clustercompliancedetailreports
    shortNames:
    - compliancedetail
    singular: clustercompliancedetailreport
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: The age of the report
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: The number of checks that failed with Danger status
      jsonPath: .report.summary.failCount
      name: Fail
      priority: 1
      type: integer
    - description: The number of checks that passed
      jsonPath: .report.summary.passCount
      name: Pass
      priority: 1
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
