---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exposedsecretreports.aquasecurity.github.io
  labels:
    app.kubernetes.io/managed-by: trivy-operator
    app.kubernetes.io/version: "0.1.0"
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: |
            ExposedSecretReport summarizes exposed secrets in plaintext files built into container images.
          type: object
          required:
            - apiVersion
            - kind
            - metadata
            - report
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            report:
              description: |
                Report is the actual exposed secret report data.
              type: object
              required:
                - updateTimestamp
                - scanner
                - artifact
                - summary
                - secrets 
              properties:
                updateTimestamp:
                  description: |
                    UpdateTimestamp is a timestamp representing the server time in UTC when this report was updated.
                  type: string
                  format: date-time
                scanner:
                  description: |
                    Scanner is the scanner that generated this report.
                  type: object
                  required:
                    - name
                    - vendor
                    - version
                  properties:
                    name:
                      description: |
                        Name the name of the scanner.
                      type: string
                    vendor:
                      description: |
                        Vendor the name of the vendor providing the scanner.
                      type: string
                    version:
                      description: |
                        Version the version of the scanner.
                      type: string
                registry:
                  description: |
                    Registry is the registry the Artifact was pulled from.
                  type: object
                  properties:
                    server:
                      description: |
                        Server the FQDN of registry server.
                      type: string
                artifact:
                  description: |
                    Artifact represents a standalone, executable package of software that includes everything needed to
                    run an application.
                  type: object
                  properties:
                    repository:
                      description: |
                        Repository is the name of the repository in the Artifact registry.
                      type: string
                    digest:
                      description: |
                        Digest is a unique and immutable identifier of an Artifact.
                      type: string
                    tag:
                      description: |
                        Tag is a mutable, human-readable string used to identify an Artifact.
                      type: string
                    mimeType:
                      description: |
                        MimeType represents a type and format of an Artifact.
                      type: string
                summary:
                  description: |
                    Summary is the exposed secrets counts grouped by Severity.
                  type: object
                  required:
                    - criticalCount
                    - highCount
                    - mediumCount
                    - lowCount
                  properties:
                    criticalCount:
                      description: |
                        CriticalCount is the number of exposed secrets with Critical Severity.
                      type: integer
                      minimum: 0
                    highCount:
                      description: |
                        HighCount is the number of exposed secrets with High Severity.
                      type: integer
                      minimum: 0
                    mediumCount:
                      description: |
                        MediumCount is the number of exposed secrets with Medium Severity.
                      type: integer
                      minimum: 0
                    lowCount:
                      description: |
                        LowCount is the number of exposed secrets with Low Severity.
                      type: integer
                      minimum: 0
                secrets:
                  description: |
                    Exposed secrets is a list of passwords, api keys, tokens and others items found in the Artifact.
                  type: array
                  items:
                    type: object
                    required:
                      - target
                      - ruleID
                      - title 
                      - category 
                      - severity
                      - match
                    properties:
                      target:
                        description: |
                          Target is where the exposed secret was found.
                        type: string
                      ruleID:
                        description: |
                          RuleID is rule the identifier.
                        type: string
                      title:
                        type: string
                      category:
                        type: string
                      severity:
                        type: string
                        enum:
                          - CRITICAL
                          - HIGH
                          - MEDIUM
                          - LOW
                      match:
                        description: |
                          Match where the exposed rule matched.
                        type: string
      additionalPrinterColumns:
        - jsonPath: .report.artifact.repository
          type: string
          name: Repository
          description: The name of image repository
        - jsonPath: .report.artifact.tag
          type: string
          name: Tag
          description: The name of image tag
        - jsonPath: .report.scanner.name
          type: string
          name: Scanner
          description: The name of the exposed secret scanner
        - jsonPath: .metadata.creationTimestamp
          type: date
          name: Age
          description: The age of the report
        - jsonPath: .report.summary.criticalCount
          type: integer
          name: Critical
          description: The number of critical exposed secrets
          priority: 1
        - jsonPath: .report.summary.highCount
          type: integer
          name: High
          description: The number of high exposed secrets
          priority: 1
        - jsonPath: .report.summary.mediumCount
          type: integer
          name: Medium
          description: The number of medium exposed secrets
          priority: 1
        - jsonPath: .report.summary.lowCount
          type: integer
          name: Low
          description: The number of low exposed secrets
          priority: 1
  scope: Namespaced
  names:
    singular: exposedsecretreport
    plural: exposedsecretreports
    kind: ExposedSecretReport
    listKind: ExposedSecretReportList
    shortNames:
      - exposedsecret 
      - exposedsecrets
