---
# End 2 End on CRON schedule (every night) or on demand.
name: End to End Testing

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

env:
  GO_VERSION: "1.19.1"

# Disable permissions granted to the GITHUB_TOKEN for all the available scopes.
permissions: {}

jobs:
  e2e-testing:
    name: End to End Testing
    runs-on: ubuntu-20.04
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    permissions:
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.7.0
          args: release -f=goreleaser-e2e.yaml --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: 1
      - name: Login to docker.io registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag and push image
        run: |
          docker tag aquasec/trivy-operator:${{ github.sha }}-amd64 aquasec/trivy-operator:e2e
          docker push aquasec/trivy-operator:e2e
      - name: Setup Kubernetes cluster (KIND)
        uses: helm/kind-action@v1.4.0
      - name: Test connection to Kubernetes cluster
        run: |
          kubectl cluster-info
          kubectl wait --for=condition=Ready nodes --all --timeout=300s
          kubectl describe node
      - name: kuttl - End to End tests
        run: |
          mkdir -p ./bin
          curl -L https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64 -o ./bin/kuttl;
          chmod +x ./bin/kuttl;
          ./bin/kuttl test --start-kind=false --config tests/config/kuttl.yaml
