---
name: End to End Testing
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *
env:
  GO_VERSION: 1.19.1
jobs:
  e2e-testing:
    name: End to End Testing
    runs-on: ubuntu-20.04
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Release snapshot
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.7.0
          args: release -f=goreleaser-e2e.yaml --snapshot --skip-publish --rm-dist
      - name: Install kind and create cluster
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster
          curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Test connection to Kubernetes cluster
        run: |
          kubectl cluster-info
          kubectl wait --for=condition=Ready nodes --all --timeout=300s
          kubectl describe node
      - name: Load operator image to cluster
        run: >
          docker tag ghcr.io/aquasecurity/trivy-operator:${{ github.sha }}-amd64
          ghcr.io/aquasecurity/trivy-operator:e2e

          docker save -o trivy-operator.tar ghcr.io/aquasecurity/trivy-operator:e2e

          kind load image-archive trivy-operator.tar
      - name: Init E2E tests (Install kuttl & helm)
        run: >
          mkdir -p ./bin

          curl -L https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64 -o ./bin/kuttl;

          chmod +x ./bin/kuttl;

          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

          chmod 700 get_helm.sh

          ./get_helm.sh
      - name: Image scan mode producing vulnerability reoport test
        run: >
          ./bin/kuttl test --start-kind=false --config tests/config/image-mode.yaml

          ./tests/resources-cleanup.sh > /dev/null 2>&1
      - name: Files System scan mode producing vulnerability reoport test
        run: |
          ./bin/kuttl test --start-kind=false --config tests/config/fs-mode.yaml
          ./tests/resources-cleanup.sh > /dev/null 2>&1
      - name: Client/server mode producing vulnerability reoport test
        run: >
          ./bin/kuttl test --start-kind=false --config
          tests/config/client-server.yaml

          ./tests/resources-cleanup.sh > /dev/null 2>&1
      - name: Node scan producing clusterinfraassessmentreport
        run: >
          ./bin/kuttl test --start-kind=false --config
          tests/config/node-collector.yaml

          ./tests/resources-cleanup.sh > /dev/null 2>&1
      - name: Delete kind cluster
        run: |
          kind delete cluster
