name: Sync from upstream

on:
  schedule:
    - cron: '0 7 */7 * *' # At 07:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-app-trivy-operator-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          # Fetch tags from upstream repo
          git fetch https://github.com/aquasecurity/trivy-operator --tags
          # Remove release candidates local tags
          git tag -d $(git tag -l | grep "\-rc")
          git push --tags
