name: "Lint PR title and label"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-title-checker:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            sec
            chore
            release
            revert
      - name: Label the PR
        uses: gerrymanoim/pr-prefix-labeler@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
