name: Chart-Content
on:
  pull_request_target:
    types:
      - closed
    paths:
      - deploy/helm/Chart.yaml

jobs:
  appVersion-validation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # was: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"

      - name: Read Chart.yaml appVersion
        id: chart_version
        run: |
          app_version=$(grep -E '^appVersion:' deploy/helm/Chart.yaml | awk '{print $2}')
          echo "app_version=$app_version" >> "$GITHUB_OUTPUT"

      - name: Repository Dispatch Publish Helm Chart
        if: ${{ steps.latest_tag.outputs.tag == steps.chart_version.outputs.app_version }}
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # was: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: publish-chart
          client-payload: '{"action": "chart-release"}'
